service: webhook-proxy

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}

  environment:
    BACKEND_SERVICE_PARAMETER_STORE_ROOT: "${env:BACKEND_SERVICE_PARAMETER_STORE_ROOT}"
    AWS_REGION: ${self:provider.region}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParametersByPath"
      Resource:
        - "Fn::Join":
            - ":"
            - - "arn:aws:ssm"
              - Ref: "AWS::Region"
              - Ref: "AWS::AccountId"
              - "parameter/*"

functions:
  webhook:
    handler: index.handler
    events:
      - http:
          path: slack/webhooks/{backendServiceId}
          method: post
          request:
            parameters:
              paths:
                backendServiceId: true
